apiVersion: batch/v1
kind: Job
metadata:
  name: myjob
  namespace: lab
spec:
  template:
    spec:
      containers:
      - name: backup
        image: busybox
        command: ["/bin/sh"]
        args: ["-c", "echo 'running my job...'; exit $(($RANDOM%2))"]
      restartPolicy: Never
  backoffLimit: 20  # max retries, default: 6
  parallelism: 3
  completions: 6
