apiVersion: v1
kind: Pod
metadata:
  name: mypod3
  namespace: lab
  labels:
    app: logger
# START OMIT
# ...
spec:
  volumes:
  - name: shared-data
    emptyDir: {}
  containers:
  - name: mypod
    image: nginx
    ports:
    - containerPort: 80
    volumeMounts:
    - name: shared-data
      mountPath: /usr/share/nginx/html
  - name: date-writer
    image: busybox
    volumeMounts:
    - name: shared-data
      mountPath: /pod-data
    command: ['sh', '-c', 'while true; do date > /pod-data/index.html; sleep 5; done']
# END OMIT
