apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: lab
spec:
  containers:
  - name: mypod
    image: mongodb
    env:
    - name: DB_USERNAME
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: username
    - name: DB_PASSWORD
      valueFrom:
        secretKeyRef:
          name: db-user-pass
          key: password
