apiVersion: v1
kind: Pod
metadata:
  name: readiness-test
  namespace: lab
spec:
  containers:
  - name: readiness
    image: busybox
    args:
    - /bin/sh
    - -c
    - sleep 600
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - "[ $(($RANDOM%2)) -eq 0 ]"
      initialDelaySeconds: 5
      periodSeconds: 3
      failureThreshold: 1
