apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: lab
spec:
  volumes:
  - name: vol1
    secret:
      secretName: db-user-pass
  containers:
  - name: mypod
    image: mongodb
    volumeMounts:
    - name: vol1
      mountPath: "/etc/foo"
      readOnly: true
