apiVersion: v1
kind: Pod
metadata:
  name: mypod
  namespace: lab
  labels:
    app: myapp
spec:
  containers:
  - name: mypod1
    image: nginx
    ports:
    - containerPort: 80
    env:
    - name: APP_NAME
      valueFrom:
        configMapKeyRef:
          name: myconfigmap
          key: appname
